# Generated by Django 2.1.7 on 2019-07-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearification', '0002_clearifications_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearifications',
            name='judge_answer',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
    ]
