# Generated by Django 2.1.3 on 2018-11-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=500)),
                ('problem_file', models.FileField(blank=True, upload_to='offlineProblemData/problemset')),
                ('problem_time_limit', models.FloatField(default=2.0)),
                ('problem_input', models.FileField(blank=True, upload_to='offlineProblemData/problemset_input')),
                ('problem_output', models.FileField(blank=True, upload_to='offlineProblemData/problemset_output')),
                ('total_solve', models.IntegerField(default=0)),
                ('total_submit', models.IntegerField(default=0)),
                ('special_judge', models.BooleanField(default=False)),
            ],
        ),
    ]
