# Generated by Django 2.1.2 on 2018-11-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest_problemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=5)),
                ('problem_name', models.CharField(max_length=300)),
                ('problem_file', models.FileField(upload_to='contestData/problemset/')),
                ('problem_time_limit', models.FloatField(default=2.0)),
                ('problem_input', models.FileField(upload_to='contestData/problemset_input/')),
                ('problem_out', models.FileField(upload_to='contestData/problemset_output/')),
                ('total_submit', models.IntegerField(default=0)),
                ('total_solve', models.IntegerField(default=0)),
                ('special_judge', models.BooleanField(default=False)),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
            ],
        ),
    ]
