# Generated by Django 2.1.2 on 2018-11-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_problemset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_problemset',
            name='problem_file',
            field=models.FileField(blank=True, upload_to='contestData/problemset/'),
        ),
        migrations.AlterField(
            model_name='contest_problemset',
            name='problem_input',
            field=models.FileField(blank=True, upload_to='contestData/problemset_input/'),
        ),
        migrations.AlterField(
            model_name='contest_problemset',
            name='problem_out',
            field=models.FileField(blank=True, upload_to='contestData/problemset_output/'),
        ),
    ]
