# Generated by Django 2.1.2 on 2018-11-20 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0003_auto_20181119_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_result', models.CharField(default='Submitted', max_length=50)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.FileField(upload_to='contestData/user_submission/')),
                ('language', models.CharField(max_length=50)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest_problemset')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
