# Generated by Django 2.1.2 on 2018-11-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contestant_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant_point',
            old_name='point',
            new_name='penalty',
        ),
        migrations.AddField(
            model_name='contestant_point',
            name='solve',
            field=models.IntegerField(default=0),
        ),
    ]
